force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi_output_dir/objects/Store__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Store</label>
    
    <nameField>
        
        <label>Store Name</label>
        
        
        <type>Text</type>
        
    </nameField>
    
    <pluralLabel>Stores</pluralLabel>
    
    
    <sharingModel>ReadWrite</sharingModel>
    
    
</CustomObject>

mdapi_output_dir/objects/Supplier__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Supplier</label>
    
    <nameField>
        
        <label>Supplier Name</label>
        
        
        <type>Text</type>
        
    </nameField>
    
    <pluralLabel>Suppliers</pluralLabel>
    
    
    <sharingModel>ReadWrite</sharingModel>
    
    
</CustomObject>

mdapi_output_dir/objects/Supplier_Order__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Supplier Order</label>
    
    <nameField>
        
        <label>Supplier Order Name</label>
        
        
        <type>Text</type>
        
    </nameField>
    
    <pluralLabel>Supplier Orders</pluralLabel>
    
    
    <sharingModel>ControlledByParent</sharingModel>
    
    
<fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        
    <fullName>Item__c</fullName>
        
    <description>The item name is the name of item the supplier</description>
        
        
    <label>Item Name</label>
        
    <length>20</length>
        
    <required>true</required>
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Order_Number__c</fullName>
        
    <description>This is intended to truck the order number, unique number.</description>
        
    <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        
    <externalId>true</externalId>
        
    <label>Order Number</label>
        
        
        
    <type>AutoNumber</type>
        
</fields>
    <fields>
        
    <fullName>Quantity__c</fullName>
        
        
    <label>Quantity</label>
        
    <precision>18</precision>
        
        
    <scale>0</scale>
        
        
        
    <type>Number</type>
        
        
</fields>
    <fields>
        
    <fullName>Shipping_Address__c</fullName>
        
        
        
    <label>Shipping Address</label>
        
    <length>100</length>
        
        
        
        
    <type>Text</type>
        
    <unique>true</unique>
        
</fields>
    <fields>
        
    <fullName>Store__c</fullName>
        
        
    <label>Store</label>
        
    <referenceTo>Store__c</referenceTo>
        
    <relationshipLabel>Supplier Orders</relationshipLabel>
        
    <relationshipName>Supplier_Orders</relationshipName>
        
    <relationshipOrder>0</relationshipOrder>
        
        
        
        
    <type>MasterDetail</type>
        
        
</fields>
    <fields>
        
    <fullName>Supplier__c</fullName>
        
        
    <label>Supplier</label>
        
    <referenceTo>Supplier__c</referenceTo>
        
    <relationshipLabel>Supplier Orders</relationshipLabel>
        
    <relationshipName>Supplier_Orders</relationshipName>
        
    <relationshipOrder>1</relationshipOrder>
        
        
        
        
    <type>MasterDetail</type>
        
        
</fields>
    <fields>
        
    <fullName>Tax_Rate__c</fullName>
        
        
    <label>Tax Rate</label>
        
    <precision>18</precision>
        
        
    <scale>0</scale>
        
        
        
    <type>Percent</type>
        
</fields>
    <fields>
        
    <fullName>Total_Cost__c</fullName>
        
        
    <formula>(Cost__c  *  Quantity__c)  + (Tax_Rate__c * ( Cost__c  * Quantity__c) )</formula>
        
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        
    <label>Total Cost</label>
        
    <precision>18</precision>
        
        
    <scale>2</scale>
        
        
        
    <type>Number</type>
        
        
</fields>
</CustomObject>

force-app/main/default/classes/Supplier.cls
public class Supplier {
    Supplier_Order__c cont = new Supplier_Order__c();
    public  Supplier_Order__c sup{get;set;}
    public List<Supplier_Order__c> s{get;set;}
    public List<Supplier_Order__c> lists = new List<Supplier_Order__c>();
    
    Public Supplier(){
        sup = new  Supplier_Order__c();
        s= new List<Supplier_Order__c>();
        s.add(cont);
    }
    public List<SelectOption> getStore(){
        List<SelectOption> listOption = new List<SelectOption>();
        List<Schema.PicklistEntry> listItems = Supplier_Order__c.Store__c.getDescribe().getPickListValues();
        for(Schema.PicklistEntry sc: listItems){
            listOption.add(new SelectOption(sc.getValue(), sc.getLabel()));
        }
       return ListOption;
    }
	
    public List<SelectOption> getItem(){
        List<SelectOption> listOption = new List<SelectOption>();
        List<Schema.PicklistEntry> listItems = Supplier_Order__c.Item__c.getDescribe().getPickListValues();
        for(Schema.PicklistEntry sc: listItems){
            listOption.add(new SelectOption(sc.getValue(), sc.getLabel()));
        }
        
        
        return ListOption;
    }
  
    public List<SelectOption> getSupplier(){
        List<SelectOption> listOption = new List<SelectOption>();
        List<Schema.PicklistEntry> listItems = Supplier_Order__c.Supplier__c.getDescribe().getPickListValues();
        for(Schema.PicklistEntry sc: listItems){
            listOption.add(new SelectOption(sc.getValue(), sc.getLabel()));
        }
        
        
        return ListOption;
    }
    
    public List<SelectOption> getTax(){
        List<SelectOption> listOption = new List<SelectOption>();
        List<Schema.PicklistEntry> listItems = Supplier_Order__c.Tax_Rate__c.getDescribe().getPickListValues();
        for(Schema.PicklistEntry sc: listItems){
            listOption.add(new SelectOption(sc.getValue(), sc.getLabel()));
        }
        
        
        return ListOption;
    }
  
        
     public void getData(){
             insert sup;
        
    }
   public void getContact(){
      List< Supplier_Order__c> supers=[SELECT Name,Supplier__c, Store__c,Cost__c,Quantity__c, Order_Number__c,Total_Cost__c,
             Shipping_Address__c,Item__c FROM Supplier_Order__c ];  
        for(Supplier_Order__c c:supers ){
                Supplier_Order__c cnts= new Supplier_Order__c(); 
                cnts.Name = c.Name;
               // cnts.Supplier__c = c.Supplier__c;
                cnts.Store__c = c.Store__c;
                cnts.Cost__c = c.Cost__c;
                cnts.Quantity__c=c.Quantity__c;
                 cnts.Shipping_Address__c = c.Shipping_Address__c;
                 //cnts.Item__c = c.Item__c;
                s.add(cnts);   
        } }
    
   
    
}