force-app/main/default/objects/Product2/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Standard_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi_output_dir/objects/Product__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Product</label>
    
    <nameField>
        
        <displayFormat>Product-{00000}</displayFormat>
        
        <label>Product Number</label>
        
        
        <type>AutoNumber</type>
        
    </nameField>
    
    <pluralLabel>Products</pluralLabel>
    
    
    
    <sharingModel>ControlledByParent</sharingModel>
    
    
    <fields>
        
    <fullName>Store__c</fullName>
        
        
    <label>Store</label>
        
    <referenceTo>Store__c</referenceTo>
        
    <relationshipLabel>Products</relationshipLabel>
        
    <relationshipName>Products</relationshipName>
        
    <relationshipOrder>0</relationshipOrder>
        
        
        
        
    <type>MasterDetail</type>
        
        
</fields>
</CustomObject>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RId-{0000}</displayFormat>
        <label>Receipt ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi_output_dir/objects/Store__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Store</label>
    
    <nameField>
        
        <label>Store Name</label>
        
        
        <type>Text</type>
        
    </nameField>
    
    <pluralLabel>Stores</pluralLabel>
    
    
    <sharingModel>ReadWrite</sharingModel>
    
    
</CustomObject>

mdapi_output_dir/objects/Transaction__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Transaction</label>
    
    <nameField>
        
        <displayFormat>Transaction-{00000}</displayFormat>
        
        <label>Transaction Number</label>
        
        
        <type>AutoNumber</type>
        
    </nameField>
    
    <pluralLabel>Transactions</pluralLabel>
    
    
    <sharingModel>ControlledByParent</sharingModel>
    
    
    <fields>
        
    <fullName>Store__c</fullName>
        
        
    <label>Store</label>
        
    <referenceTo>Store__c</referenceTo>
        
    <relationshipLabel>Transactions</relationshipLabel>
        
    <relationshipName>Transactions</relationshipName>
        
    <relationshipOrder>0</relationshipOrder>
        
        
        
        
    <type>MasterDetail</type>
        
        
</fields>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_Time__c</fullName>
    <label>Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Sub_Total__c.field-meta.xml
<CustomField>
    <fullName>Sub_Total__c</fullName>
    <label>Sub-Total</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TransactionController.cls
public class TransactionController {
    public Transaction__c trans {get;set;}
    public String myInput{get;set;}
  	public String myOutput{get;set;}
    public Decimal subTotal {get;set;}
    //public List<PriceBookEntry> prodPrice {get;set;}
    //public Map<String, Product2> tempMap {get;set;}
    
    public TransactionController() {}
    
    public void search() {
        //Grab and save input from VF page
        myOutput = myInput;
        
        //Query transaction based on above input
        trans = [SELECT Name, Store__r.Name, Date_Time__c, 
                 (SELECT Product__r.ProductCode, Product__r.Name, Product__r.Price__c From Receipts__r) 
                 FROM Transaction__c WHERE Name = :myOutput];
        
        //Variable to calculate sub-total
        Decimal subTotal = 0;
        
        //Grab list of receipts from above query
        List<Receipt__c> queryReceipt = trans.Receipts__r;
        
        //Loop through above list of receipts 
        for(Receipt__c r : queryReceipt) {
            //Add each products price from receipts to sub-total
            subTotal += r.Product__r.Price__c;
        }
        
        //Calculate tax ansd total from sub-total
        Decimal tax = subTotal * 0.075;
        Decimal total = subTotal + tax;
        
        trans.Sub_Total__c = subTotal;
        trans.Tax__c = tax;
        trans.Total__c = total;
        
        //price = trans.Receipts__r;
        //Product2 prodRef = new Product2();
        
      	//List<Product2> unitPrice = new List<Product2>();
        //for(Receipt__c r : price) {
            //prodRef.Id = r.Product__c;
            //unitPrice.add(prodRef);
        //}
       
        //tempMap = new Map<String, Product2>(price);
        
        //prodPrice = [SELECT UnitPrice FROM PriceBookEntry WHERE Product2Id IN :unitPrice];
	}
    
    //Query list price from PriceBookEntry
    //SELECT Product2.Name, PriceBook2.Name, UnitPrice FROM PricebookEntry
    //
}