force-app/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>FDBK-{0000}</displayFormat>
        <label>Feedback Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Feedback__c/fields/Feedback_Q1__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Q1__c</fullName>
    <label>Feedback Q1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>Twitter</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Podcast</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Feedback_Q2__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Q2__c</fullName>
    <label>Feedback Q2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Feedback_Q3__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Q3__c</fullName>
    <label>Feedback Q3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Feedback_Q4__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Q4__c</fullName>
    <label>Feedback Q4</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Feedback_Q5__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Q5__c</fullName>
    <label>Feedback Q5</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/FeedbackControllerTest.cls
/**************************************************************
* FeedbackControllerTest.apxc
* Author: Evan DeVizio
* Created: 8/16/21
* Modified: 8/17/21
***************************************************************/
@isTest
public class FeedbackControllerTest {
	
    @isTest
    public static void testFeedback(){
        Boolean pass = false;
        Feedback__c testFdbk = FeedbackControllerC.initFeedback();
        testFdbk.Feedback_Q5__c = 'TEST';
        insert(testFdbk);
        
        List<Feedback__c> queryResult = [SELECT Id, Feedback_Q5__c FROM Feedback__c WHERE Feedback_Q5__c = 'TEST' LIMIT 1];
        for(Feedback__c res : queryResult) {
            if(res.Feedback_Q5__c == testFdbk.Feedback_Q5__c) {
                pass = true;
            }
        }
        
        Feedback__c testFdbkNeg = new Feedback__c(Feedback_Q1__c='Google', Feedback_Q2__c='5', 
                                           Feedback_Q3__c='5', Feedback_Q4__c='5', 
                                           Feedback_Q5__c='This is a different comment.');      

        insert(testFdbkNeg);
		Feedback__c testFdbkNegResult = [SELECT Id, Feedback_Q5__c FROM Feedback__c WHERE Feedback_Q5__c = :testFdbkNeg.Feedback_Q5__c];
        system.debug(testFdbk.Feedback_Q5__c == testFdbkNegResult.Feedback_Q5__c);
        system.assert(pass);
        system.assertEquals(false, (testFdbk.Feedback_Q5__c == testFdbkNegResult.Feedback_Q5__c));
    }
}