mdapi_output_dir/objects/Customer__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Customer</label>
    
    <nameField>
        
        <displayFormat>Customer-{00000}</displayFormat>
        
        <label>Customer Number</label>
        
        
        <type>AutoNumber</type>
        
    </nameField>
    
    <pluralLabel>Customers</pluralLabel>
    
    
    <sharingModel>ReadWrite</sharingModel>
    
    
    <fields>
        
    <fullName>Credit_Card_Type__c</fullName>
        
        
    <label>Credit Card Type</label>
        
        
        
        
    <type>Picklist</type>
        
    <valueSet>
            
        <restricted>true</restricted>
            
        <valueSetName>Credit_Card_Type</valueSetName>
            
    </valueSet>
        
</fields>
    <fields>
        
    <fullName>Email__c</fullName>
        
    <caseSensitive>true</caseSensitive>
        
        
    <label>Email</label>
        
        
        
        
    <type>Email</type>
        
    <unique>true</unique>
        
</fields>
    <fields>
        
    <fullName>First_Name__c</fullName>
        
        
    <label>First Name</label>
        
    <length>30</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/password__c.field-meta.xml
<CustomField>
    <fullName>password__c</fullName>
    <label>password</label>
    <length>20</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

mdapi_output_dir/objects/Employee__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Employee</label>
    
    <nameField>
        
        <displayFormat>Employee-{0000}</displayFormat>
        
        <label>Employee Number</label>
        
        
        <type>AutoNumber</type>
        
    </nameField>
    
    <pluralLabel>Employees</pluralLabel>
    
    
    <sharingModel>ControlledByParent</sharingModel>
    
    
    <fields>
        
    <fullName>Email__c</fullName>
        
        
    <label>Email</label>
        
        
        
        
    <type>Email</type>
        
        
</fields>
    <fields>
        
    <fullName>First_Name__c</fullName>
        
        
    <label>First Name</label>
        
    <length>30</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>20</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/globalValueSets/Credit_Card_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>American Express</fullName>
    </customValue>
    <customValue>
        <fullName>Visa</fullName>
    </customValue>
    <customValue>
        <fullName>Mastercard</fullName>
    </customValue>
    <customValue>
        <fullName>Discover</fullName>
    </customValue>
    <masterLabel>Credit Card Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SignInController.cls
public class SignInController {

    
    @AuraEnabled
    public static sObject checkEmailPassword(String email, String password) {
		
        Boolean isVerified = false;
        String checkPassword;
        sObject loggedIn;
        String searchQuery = 'FIND \'' + email + '\'IN ALL FIELDS RETURNING Customer__c(Id,Email__c,First_Name__c, Credit_Card_Type__c, Password__c), Employee__c(Id,Email__c,First_Name__c, Password__c)';  
        List<List<Sobject>> results = search.query(searchQuery);
        if(results[0].size() != 0) {
           Customer__c[] searchCustomers = (Customer__c[])results[0];
            checkPassword = searchCustomers[0].Password__c;
            if(checkPassword == password) {
                loggedIn = searchCustomers[0];
            }
        } else if(results[1].size() != 0) {
          Employee__c[] searchEmployees = (Employee__c[])results[1];
            checkPassword = searchEmployees[0].Password__c;
             if(checkPassword == password) {
                loggedIn = searchEmployees[0];
        	}
        }
		system.debug(loggedIn);
        return loggedIn;
    }
    

   
}