mdapi_output_dir/objects/Customer__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Customer</label>
    
    <nameField>
        
        <displayFormat>Customer-{00000}</displayFormat>
        
        <label>Customer Number</label>
        
        
        <type>AutoNumber</type>
        
    </nameField>
    
    <pluralLabel>Customers</pluralLabel>
    
    
    <sharingModel>ReadWrite</sharingModel>
    
    
    <fields>
        
    <fullName>First_Name__c</fullName>
        
        
    <label>First Name</label>
        
    <length>30</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
</CustomObject>

force-app/main/default/objects/Product2/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Standard_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi_output_dir/objects/Product__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Product</label>
    
    <nameField>
        
        <displayFormat>Product-{00000}</displayFormat>
        
        <label>Product Number</label>
        
        
        <type>AutoNumber</type>
        
    </nameField>
    
    <pluralLabel>Products</pluralLabel>
    
    
    
    <sharingModel>ControlledByParent</sharingModel>
    
    
    <fields>
        
    <fullName>Store__c</fullName>
        
        
    <label>Store</label>
        
    <referenceTo>Store__c</referenceTo>
        
    <relationshipLabel>Products</relationshipLabel>
        
    <relationshipName>Products</relationshipName>
        
    <relationshipOrder>0</relationshipOrder>
        
        
        
        
    <type>MasterDetail</type>
        
        
</fields>
</CustomObject>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RId-{0000}</displayFormat>
        <label>Receipt ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi_output_dir/objects/Store__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Store</label>
    
    <nameField>
        
        <label>Store Name</label>
        
        
        <type>Text</type>
        
    </nameField>
    
    <pluralLabel>Stores</pluralLabel>
    
    
    <sharingModel>ReadWrite</sharingModel>
    
    
</CustomObject>

mdapi_output_dir/objects/Transaction__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Transaction</label>
    
    <nameField>
        
        <displayFormat>Transaction-{00000}</displayFormat>
        
        <label>Transaction Number</label>
        
        
        <type>AutoNumber</type>
        
    </nameField>
    
    <pluralLabel>Transactions</pluralLabel>
    
    
    <sharingModel>ControlledByParent</sharingModel>
    
    
<fields>
        
    <fullName>Customer__c</fullName>
        
        
    <label>Customer</label>
        
    <referenceTo>Customer__c</referenceTo>
        
    <relationshipLabel>Transactions</relationshipLabel>
        
    <relationshipName>Transactions</relationshipName>
        
    <relationshipOrder>1</relationshipOrder>
        
        
        
        
    <type>MasterDetail</type>
        
        
</fields>
    <fields>
        
    <fullName>Store__c</fullName>
        
        
    <label>Store</label>
        
    <referenceTo>Store__c</referenceTo>
        
    <relationshipLabel>Transactions</relationshipLabel>
        
    <relationshipName>Transactions</relationshipName>
        
    <relationshipOrder>0</relationshipOrder>
        
        
        
        
    <type>MasterDetail</type>
        
        
</fields>
</CustomObject>

force-app/main/default/classes/ProductControllerTest.cls
@isTest
private class ProductControllerTest {
    
    @isTest
    static void testGetReceipts() {
        // Making test data
    	Product2 test = new Product2(Name='Test1');
        Product2 test2 = new Product2(Name='Test2');
        insert test;
        insert test2;
        List<Id> listIds = new List<Id>();
        listIds.add(test.Id);
        listIds.add(test2.Id);
        
        //Testing the method
        List<Id> listProducts = ProductController.getAllProducts();
       	
        system.assertEquals(listIds, listProducts);
       	
    }
	
    @isTest
    static void testGetProduct() {
        //making test data
        Product2 test = new Product2(Name='Testing',Price__c=40);
        insert test;
        Id productId = test.Id;
        
       	//testing method
        Product2 testProduct = ProductController.getProduct(productId);
        system.assertEquals(test.Name, testProduct.Name);
        system.assertEquals(test.Price__c, testProduct.Price__c);
    }
    
    @isTest
    static void testNewTransaction() {
        
        //making test data
        Customer__c newCustomer = new Customer__c(First_Name__c='Mike');
        Store__c newStore = new Store__c(Name='TestingStore');
        insert newCustomer;
        insert newStore;
        
        //testing method
        ProductController.newTransaction(newCustomer.Id,newStore.Id);
        Transaction__c testTransaction = [SELECT ID,Customer__c,Store__c FROM Transaction__c][0];
       
        system.assertEquals(newCustomer.Id, testTransaction.Customer__c);
        system.assertEquals(newStore.Id, testTransaction.Store__c);
    }
    
    @isTest 
    static void newReceipts() {
        //making test data
        Customer__c testCustomer = new Customer__c();
        	insert testCustomer;
        Store__c newStore = new Store__c(Name='Test Store');
        	insert newStore;
        Product2 testProduct = new Product2(Name='Test Product');
        	insert testProduct;
        Integer quantity = 3;
        Transaction__c testTransaction = new Transaction__c(Store__c = newStore.Id, Customer__c = testCustomer.Id);
        Transaction__c testTransaction2 = new Transaction__c(Store__c = newStore.Id, Customer__c = testCustomer.Id);
        insert testTransaction;
        insert testTransaction2;
        
        //testing the method that the latest transaction got receipts linked to it
        ProductController.newReceipts(testCustomer.Id, testProduct.Id, quantity);
        List<Receipt__c> listReceipts = [SELECT Id,Transaction__c,Product__c FROM Receipt__c];
        Receipt__c testReceipt = listReceipts[0];
        system.assertEquals(listReceipts.size(), 3);
        system.assertEquals(testTransaction2.Id, testReceipt.Transaction__c);
        
    }
    
    
    
    
    
    
}