mdapi_output_dir/objects/Customer__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Customer</label>
    
    <nameField>
        
        <displayFormat>Customer-{00000}</displayFormat>
        
        <label>Customer Number</label>
        
        
        <type>AutoNumber</type>
        
    </nameField>
    
    <pluralLabel>Customers</pluralLabel>
    
    
    <sharingModel>ReadWrite</sharingModel>
    
    
<fields>
        
    <fullName>City__c</fullName>
        
        
    <label>City</label>
        
    <length>30</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Credit_Card_Type__c</fullName>
        
        
    <label>Credit Card Type</label>
        
        
        
        
    <type>Picklist</type>
        
    <valueSet>
            
        <restricted>true</restricted>
            
        <valueSetName>Credit_Card_Type</valueSetName>
            
    </valueSet>
        
</fields>
    <fields>
        
    <fullName>First_Name__c</fullName>
        
        
    <label>First Name</label>
        
    <length>30</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>State__c</fullName>
        
        
    <inlineHelpText>Use state&apos;s initials i.e. GA-Georgia</inlineHelpText>
        
    <label>State</label>
        
    <length>2</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Street_Address__c</fullName>
        
        
    <label>Street Address</label>
        
    <length>40</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Zip__c</fullName>
        
        
    <label>Zip</label>
        
    <length>10</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
</CustomObject>

force-app/main/default/objects/Product2/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi_output_dir/objects/Product__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Product</label>
    
    <nameField>
        
        <displayFormat>Product-{00000}</displayFormat>
        
        <label>Product Number</label>
        
        
        <type>AutoNumber</type>
        
    </nameField>
    
    <pluralLabel>Products</pluralLabel>
    
    
    
    <sharingModel>ControlledByParent</sharingModel>
    
    
</CustomObject>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RId-{0000}</displayFormat>
        <label>Receipt ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi_output_dir/objects/Transaction__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Transaction</label>
    
    <nameField>
        
        <displayFormat>Transaction-{00000}</displayFormat>
        
        <label>Transaction Number</label>
        
        
        <type>AutoNumber</type>
        
    </nameField>
    
    <pluralLabel>Transactions</pluralLabel>
    
    
    <sharingModel>ControlledByParent</sharingModel>
    
    
<fields>
        
    <fullName>Customer__c</fullName>
        
        
    <label>Customer</label>
        
    <referenceTo>Customer__c</referenceTo>
        
    <relationshipLabel>Transactions</relationshipLabel>
        
    <relationshipName>Transactions</relationshipName>
        
    <relationshipOrder>1</relationshipOrder>
        
        
        
        
    <type>MasterDetail</type>
        
        
</fields>
</CustomObject>

force-app/main/default/globalValueSets/Credit_Card_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>American Express</fullName>
    </customValue>
    <customValue>
        <fullName>Visa</fullName>
    </customValue>
    <customValue>
        <fullName>Mastercard</fullName>
    </customValue>
    <customValue>
        <fullName>Discover</fullName>
    </customValue>
    <masterLabel>Credit Card Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ReceiptPageController.cls
/*
Title: ReceiptPageController
Author: Milan Winter
Date Updated: 8/17/21
Description: Apex Controller for the receipt page in the aura component. Grabs a list of the products for the customer's last transaction and sends
it to the javascript controller. It also has methods to get more info for a single customer and single product.
*/

public with sharing class ReceiptPageController {
    
    
    //Grabbing a list of productIds that can be iterated over in the receiptPage component
	@AuraEnabled
    public static List<String> getReceipts(String customerId) {
        String customer = customerId;
        List<String> productIds = new List<String>();
        String currentTransactionId = [SELECT Id FROM Transaction__c WHERE Customer__c = :customer ORDER BY createdDate DESC LIMIT 1][0].Id;
        
        List<Receipt__c> receiptsList = [SELECT Id, Product__c FROM Receipt__c WHERE Transaction__c = :currentTransactionId];
        for(receipt__c r : receiptsList){
            productIds.add(r.Product__c);
        }
        return productIds;
    }
    
    @AuraEnabled
    public static Product2 getProduct(String productId) {
        Product2 selectProduct;
        if(Schema.SObjectType.Product2.isAccessible()){
          selectProduct = [SELECT Id,Name,Price__c,ProductCode FROM Product2 WHERE Id = :productId][0];
           system.debug(selectProduct);
        }
      
        return selectProduct;
    }
    
    @AuraEnabled 
    public static Customer__c getCustomer(String customerId) {
        Customer__c customer = [SELECT Id,First_Name__c, Credit_Card_Type__c, Street_Address__c, City__c, State__c,
                               Zip__c FROM Customer__c WHERE Id = :customerId][0];
        return customer;
    }
}