mdapi_output_dir/objects/Customer__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Customer</label>
    
    <nameField>
        
        <displayFormat>Customer-{00000}</displayFormat>
        
        <label>Customer Number</label>
        
        
        <type>AutoNumber</type>
        
    </nameField>
    
    <pluralLabel>Customers</pluralLabel>
    
    
    <sharingModel>ReadWrite</sharingModel>
    
    
<fields>
        
    <fullName>City__c</fullName>
        
        
    <label>City</label>
        
    <length>30</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>First_Name__c</fullName>
        
        
    <label>First Name</label>
        
    <length>30</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
</CustomObject>

force-app/main/default/objects/Product2/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Standard_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi_output_dir/objects/Store__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Store</label>
    
    <nameField>
        
        <label>Store Name</label>
        
        
        <type>Text</type>
        
    </nameField>
    
    <pluralLabel>Stores</pluralLabel>
    
    
    <sharingModel>ReadWrite</sharingModel>
    
    
<fields>
        
    <fullName>City__c</fullName>
        
        
    <label>City</label>
        
    <length>40</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
</CustomObject>

mdapi_output_dir/objects/Transaction__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Transaction</label>
    
    <nameField>
        
        <displayFormat>Transaction-{00000}</displayFormat>
        
        <label>Transaction Number</label>
        
        
        <type>AutoNumber</type>
        
    </nameField>
    
    <pluralLabel>Transactions</pluralLabel>
    
    
    <sharingModel>ControlledByParent</sharingModel>
    
    
<fields>
        
    <fullName>Customer__c</fullName>
        
        
    <label>Customer</label>
        
    <referenceTo>Customer__c</referenceTo>
        
    <relationshipLabel>Transactions</relationshipLabel>
        
    <relationshipName>Transactions</relationshipName>
        
    <relationshipOrder>1</relationshipOrder>
        
        
        
        
    <type>MasterDetail</type>
        
        
</fields>
    <fields>
        
    <fullName>Store__c</fullName>
        
        
    <label>Store</label>
        
    <referenceTo>Store__c</referenceTo>
        
    <relationshipLabel>Transactions</relationshipLabel>
        
    <relationshipName>Transactions</relationshipName>
        
    <relationshipOrder>0</relationshipOrder>
        
        
        
        
    <type>MasterDetail</type>
        
        
</fields>
</CustomObject>

force-app/main/default/classes/ReceiptPageControllerTest.cls
@isTest
private class ReceiptPageControllerTest {
	
    @isTest
    static void testGetReceipts(){
         //making test data
        Customer__c testCustomer = new Customer__c();
        	insert testCustomer;
        Store__c newStore = new Store__c(Name='Test Store');
        	insert newStore;
        Product2 testProduct = new Product2(Name='Test Product');
        	insert testProduct;
        Integer quantity = 3;
         Transaction__c testTransaction = new Transaction__c(Store__c = newStore.Id, Customer__c = testCustomer.Id);
        insert testTransaction;
        ProductController.newReceipts(testCustomer.Id, testProduct.Id, quantity);
        
        //testing the method
        List<String> actualProductIds = ReceiptPageController.getReceipts(testCustomer.Id);
        system.assertEquals(3,actualProductIds.size());
        system.assertEquals(testProduct.Id, actualProductIds[0]);
    }
    
    
    @isTest
    static void testGetProduct() {
        // making test data
        Product2 testProduct = new Product2(Name='Test Product',Price__c = 25);
        insert testProduct;
        
        //testing the method
        Product2 methodProduct = ReceiptPageController.getProduct(testProduct.Id);
        
        system.assertEquals(testProduct.Id, methodProduct.Id);
        system.assertEquals(testProduct.Price__c, methodProduct.Price__c);
    }
    
    @isTest
    
    static void testGetCustomer() {
        //making test data
        Customer__c newCustomer = new Customer__c(First_Name__c = 'Bobby',City__c ='San Francisco');
        insert newCustomer;
        
        //testing the method
      	Customer__c testCustomer = ReceiptPageController.getCustomer(newCustomer.Id);
        system.assertEquals(newCustomer.Id, testCustomer.Id);
        system.assertEquals('San Francisco',testCustomer.City__c);
    }
    
    
    
    
    
    
    
    
    
    
    
}