mdapi_output_dir/objects/Customer__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Customer</label>
    
    <nameField>
        
        <displayFormat>Customer-{00000}</displayFormat>
        
        <label>Customer Number</label>
        
        
        <type>AutoNumber</type>
        
    </nameField>
    
    <pluralLabel>Customers</pluralLabel>
    
    
    <sharingModel>ReadWrite</sharingModel>
    
    
<fields>
        
    <fullName>City__c</fullName>
        
        
    <label>City</label>
        
    <length>30</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Credit_Card_Expiration_Month__c</fullName>
        
        
    <label>Credit Card Expiration Month</label>
        
        
        
        
    <type>Picklist</type>
        
    <valueSet>
            
        <restricted>true</restricted>
            
        <valueSetName>Months</valueSetName>
            
    </valueSet>
        
</fields>
    <fields>
        
    <fullName>Credit_Card_Expiration_Year__c</fullName>
        
        
    <label>Credit Card Expiration Year</label>
        
        
        
        
    <type>Picklist</type>
        
    <valueSet>
            
        <restricted>true</restricted>
            
        <valueSetName>Future_Years</valueSetName>
            
    </valueSet>
        
</fields>
    <fields>
        
    <fullName>Credit_Card_Number__c</fullName>
        
        
    <inlineHelpText>Enter the correct format for your card including dashes.</inlineHelpText>
        
    <label>Credit Card Number</label>
        
    <length>25</length>
        
    <maskChar>X</maskChar>
        
    <maskType>creditCard</maskType>
        
        
        
        
    <type>EncryptedText</type>
        
</fields>
    <fields>
        
    <fullName>Credit_Card_Type__c</fullName>
        
        
    <label>Credit Card Type</label>
        
        
        
        
    <type>Picklist</type>
        
    <valueSet>
            
        <restricted>true</restricted>
            
        <valueSetName>Credit_Card_Type</valueSetName>
            
    </valueSet>
        
</fields>
    <fields>
        
    <fullName>Email__c</fullName>
        
    <caseSensitive>true</caseSensitive>
        
        
    <label>Email</label>
        
        
        
        
    <type>Email</type>
        
    <unique>true</unique>
        
</fields>
    <fields>
        
    <fullName>First_Name__c</fullName>
        
        
    <label>First Name</label>
        
    <length>30</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Last_Name__c</fullName>
        
        
    <label>Last Name</label>
        
    <length>30</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Phone__c</fullName>
        
        
    <label>Phone</label>
        
        
        
        
    <type>Phone</type>
        
</fields>
    <fields>
        
    <fullName>Shipping_City__c</fullName>
        
        
    <label>Shipping City</label>
        
    <length>20</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Shipping_State__c</fullName>
        
        
    <inlineHelpText>State&apos;s acronym i.e. Georgia is GA</inlineHelpText>
        
    <label>Shipping State</label>
        
    <length>2</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Shipping_Street__c</fullName>
        
        
    <label>Shipping Street</label>
        
    <length>30</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Shipping_Zip_Code__c</fullName>
        
        
    <label>Shipping Zip Code</label>
        
    <length>10</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Ship_to_Billing_Address__c</fullName>
        
    <defaultValue>false</defaultValue>
        
    <description>Is the shipping address the same as your billing address?</description>
        
        
    <label>Ship to Billing Address</label>
        
        
        
    <type>Checkbox</type>
        
</fields>
    <fields>
        
    <fullName>State__c</fullName>
        
        
    <inlineHelpText>Use state&apos;s initials i.e. GA-Georgia</inlineHelpText>
        
    <label>State</label>
        
    <length>2</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Street_Address__c</fullName>
        
        
    <label>Street Address</label>
        
    <length>40</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Zip__c</fullName>
        
        
    <label>Zip</label>
        
    <length>10</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
</CustomObject>

force-app/main/default/globalValueSets/Credit_Card_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>American Express</fullName>
    </customValue>
    <customValue>
        <fullName>Visa</fullName>
    </customValue>
    <customValue>
        <fullName>Mastercard</fullName>
    </customValue>
    <customValue>
        <fullName>Discover</fullName>
    </customValue>
    <masterLabel>Credit Card Type</masterLabel>
</GlobalValueSet>

Project 1/force-app/main/default/globalValueSets/Future_Years.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2030</fullName>
    </customValue>
    <masterLabel>Future Years</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Months.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
    </customValue>
    <customValue>
        <fullName>02</fullName>
    </customValue>
    <customValue>
        <fullName>03</fullName>
    </customValue>
    <customValue>
        <fullName>04</fullName>
    </customValue>
    <customValue>
        <fullName>05</fullName>
    </customValue>
    <customValue>
        <fullName>06</fullName>
    </customValue>
    <customValue>
        <fullName>07</fullName>
    </customValue>
    <customValue>
        <fullName>08</fullName>
    </customValue>
    <customValue>
        <fullName>09</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <masterLabel>Months</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomerPurchasePageController.cls
public with sharing class CustomerPurchasePageController {

    public String input {get;set;}
    public Customer__c customer {get;set;}
    public Boolean shippingRender {get;set;}

    public CustomerPurchasePageController(){
        shippingRender = true;
        customer = new Customer__c();
        // checkboxUpdate();
    }

    // Method used to search for the Customer input in the field at the top of the page.
    public void search(){
        /*
        if([SELECT * FROM Customer__c WHERE ((First_Name__c LIKE ('%'+input+'%')) OR (Last_Name__c LIKE ('%'+input+'%')))] == Null){
            
        }
        */
        customer = [SELECT Name, Id, First_Name__c, Last_Name__c, City__c, Credit_Card_Expiration_Month__c,
            Credit_Card_Expiration_Year__c, Credit_Card_Number__c, Credit_Card_Type__c, Email__c, Phone__c, Ship_to_Billing_Address__c,
            Shipping_City__c, Shipping_State__c, Shipping_Street__c, Shipping_Zip_Code__c, State__c, Street_Address__c,
            Zip__c
            FROM Customer__c WHERE Name = :input
            LIMIT 1];
        checkboxUpdate();
        
    }

    public void save(){
        if(customer.Id == Null){
            insert customer;
        }else{
            update customer;
        }
    }

    //  Method used to see if the checkbox field Ship_to_Billing_Address is checked in order to 
	//	change the rendering of certain objects
    public void checkboxUpdate(){
        if(customer.Ship_to_Billing_Address__c == Null){
            shippingRender = true;
        }if(customer.Ship_to_Billing_Address__c == true){
           shippingRender = false;
        } else{
            shippingRender = true;
        }
    }
}