mdapi_output_dir/objects/Customer__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Customer</label>
    
    <nameField>
        
        <displayFormat>Customer-{00000}</displayFormat>
        
        <label>Customer Number</label>
        
        
        <type>AutoNumber</type>
        
    </nameField>
    
    <pluralLabel>Customers</pluralLabel>
    
    
    <sharingModel>ReadWrite</sharingModel>
    
    
    <fields>
        
    <fullName>First_Name__c</fullName>
        
        
    <label>First Name</label>
        
    <length>30</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Last_Name__c</fullName>
        
        
    <label>Last Name</label>
        
    <length>30</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
</CustomObject>

force-app/main/default/classes/CPPTest.cls
@isTest
public class CPPTest {

    @isTest
    static void CustomerPurchasePageTest() {
       String customerId= 'Customer-00000';
       Customer__c testCustomer = new Customer__c();
       testCustomer.Id = 'TEST'; 
       testCustomer.First_Name__c = 'Test_firstName';
        testCustomer.Last_Name__c = 'Test_lastName';
        insert(testCustomer);
        
        Customer__c[] queryResult = [SELECT Id FROM Customer__c WHERE First_Name__c = 'Test_firstName' LIMIT 1];
         String recordIdTest = queryResult[0].Id;
        
        
        //Start the Test
       String recordId = CPPController.newCustomerId(recordIdTest);
        System.assertEquals(recordIdTest, testCustomer.Id);
        
        

        
        
    }
    
}