mdapi_output_dir/objects/Customer__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Customer</label>
    
    <nameField>
        
        <displayFormat>Customer-{00000}</displayFormat>
        
        <label>Customer Number</label>
        
        
        <type>AutoNumber</type>
        
    </nameField>
    
    <pluralLabel>Customers</pluralLabel>
    
    
    <sharingModel>ReadWrite</sharingModel>
    
    
    <fields>
        
    <fullName>First_Name__c</fullName>
        
        
    <label>First Name</label>
        
    <length>30</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
</CustomObject>

force-app/main/default/objects/Product2/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Standard_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi_output_dir/objects/Product__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Product</label>
    
    <nameField>
        
        <displayFormat>Product-{00000}</displayFormat>
        
        <label>Product Number</label>
        
        
        <type>AutoNumber</type>
        
    </nameField>
    
    <pluralLabel>Products</pluralLabel>
    
    
    
    <sharingModel>ControlledByParent</sharingModel>
    
    
    <fields>
        
    <fullName>Store__c</fullName>
        
        
    <label>Store</label>
        
    <referenceTo>Store__c</referenceTo>
        
    <relationshipLabel>Products</relationshipLabel>
        
    <relationshipName>Products</relationshipName>
        
    <relationshipOrder>0</relationshipOrder>
        
        
        
        
    <type>MasterDetail</type>
        
        
</fields>
</CustomObject>

mdapi_output_dir/objects/Store__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Store</label>
    
    <nameField>
        
        <label>Store Name</label>
        
        
        <type>Text</type>
        
    </nameField>
    
    <pluralLabel>Stores</pluralLabel>
    
    
    <sharingModel>ReadWrite</sharingModel>
    
    
</CustomObject>

mdapi_output_dir/objects/Transaction__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Transaction</label>
    
    <nameField>
        
        <displayFormat>Transaction-{00000}</displayFormat>
        
        <label>Transaction Number</label>
        
        
        <type>AutoNumber</type>
        
    </nameField>
    
    <pluralLabel>Transactions</pluralLabel>
    
    
    <sharingModel>ControlledByParent</sharingModel>
    
    
<fields>
        
    <fullName>Customer__c</fullName>
        
        
    <label>Customer</label>
        
    <referenceTo>Customer__c</referenceTo>
        
    <relationshipLabel>Transactions</relationshipLabel>
        
    <relationshipName>Transactions</relationshipName>
        
    <relationshipOrder>1</relationshipOrder>
        
        
        
        
    <type>MasterDetail</type>
        
        
</fields>
    <fields>
        
    <fullName>Store__c</fullName>
        
        
    <label>Store</label>
        
    <referenceTo>Store__c</referenceTo>
        
    <relationshipLabel>Transactions</relationshipLabel>
        
    <relationshipName>Transactions</relationshipName>
        
    <relationshipOrder>0</relationshipOrder>
        
        
        
        
    <type>MasterDetail</type>
        
        
</fields>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_Time__c</fullName>
    <label>Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Sub_Total__c.field-meta.xml
<CustomField>
    <fullName>Sub_Total__c</fullName>
    <label>Sub-Total</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TransactionData.cls
public class TransactionData {
    public static void addTransaction() {
        
        Store__c s = [SELECT Id, Name From Store__c LIMIT 1];
        
        
        //Customer__c c = new Customer__c(First_Name__c='Customer1');
        //upsert c;
        //Creating a List for the zombie products.
        List<Product2> ZombieProdList = [SELECT Id, Name FROM Product2 WHERE ProductCode LIKE 'P%'];
        
        
        
        //Transaction__c trans = new Transaction__c();
        //trans.Date_Time__c = Datetime.now();
        //trans.Store__c = s.Id;

        //List<Product2> p2 = new List<Product2>();
        //p2.add(ZombieProdList[0].Id);
        //trans.product__c = ;
        
        //System.debug(trans);
        
        
        
        
        //for(Integer i=0; i<5; i++) {
            //Transaction__c t = new Transaction__c();
            //t.Date_Time__c = Datetime.now();
            //t.Sub_Total__c = ;
            //t.Quantity__c = 1 + i;
            //t.Store__c = s.Id;
            //t.Customer__c = c.Id;
            //t.Product__c = [];
            //trans.add(t);
        //}
        
        //upsert trans;
        //system.debug(trans);
        
        //List<Product2> prod = new List<Product2>();
        //List<Transaction__c> trs = new List<Transaction__c>();
        //trs.add(trans[0].Id);
        //trs.add(trans[1].Id);
        
        //for(Integer i=0; i<2; i++) {
            //product2 p = new Product2(Name='Product ' + i, Store__c=s.Id, Transaction__c = trs, Price__c=(50+i));
            //prod.add(p);
        //}
        //System.debug(Prod);
    
        //Insert prod;
    }
}