mdapi_output_dir/objects/Store__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Store</label>
    
    <nameField>
        
        <label>Store Name</label>
        
        
        <type>Text</type>
        
    </nameField>
    
    <pluralLabel>Stores</pluralLabel>
    
    
    <sharingModel>ReadWrite</sharingModel>
    
    
<fields>
        
    <fullName>City__c</fullName>
        
        
    <label>City</label>
        
    <length>40</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Phone__c</fullName>
        
        
    <label>Phone</label>
        
        
        
        
    <type>Phone</type>
        
</fields>
    <fields>
        
    <fullName>State__c</fullName>
        
        
    <inlineHelpText>Only use the initials for the state i.e. GA - Georgia</inlineHelpText>
        
    <label>State</label>
        
    <length>2</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Street_Address__c</fullName>
        
        
    <label>Street Address</label>
        
    <length>40</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Zip__c</fullName>
        
        
    <label>Zip</label>
        
    <length>10</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
</CustomObject>

mdapi_output_dir/objects/Supplier__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Supplier</label>
    
    <nameField>
        
        <label>Supplier Name</label>
        
        
        <type>Text</type>
        
    </nameField>
    
    <pluralLabel>Suppliers</pluralLabel>
    
    
    <sharingModel>ReadWrite</sharingModel>
    
    
<fields>
        
    <fullName>City__c</fullName>
        
        
    <label>City</label>
        
    <length>40</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Email__c</fullName>
        
    <caseSensitive>true</caseSensitive>
        
        
    <label>Email</label>
        
        
        
        
    <type>Email</type>
        
    <unique>true</unique>
        
</fields>
    <fields>
        
    <fullName>Phone__c</fullName>
        
        
    <label>Phone</label>
        
        
        
        
    <type>Phone</type>
        
</fields>
    <fields>
        
    <fullName>State__c</fullName>
        
    <description>Use state&apos;s initials i.e. GA-Georgia</description>
        
        
    <label>State</label>
        
    <length>2</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Street_Address__c</fullName>
        
        
    <label>Street Address</label>
        
    <length>40</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Zip__c</fullName>
        
        
    <label>Zip</label>
        
    <length>10</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
</CustomObject>

mdapi_output_dir/objects/Supplier_Order__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Supplier Order</label>
    
    <nameField>
        
        <label>Supplier Order Name</label>
        
        
        <type>Text</type>
        
    </nameField>
    
    <pluralLabel>Supplier Orders</pluralLabel>
    
    
    <sharingModel>ControlledByParent</sharingModel>
    
    
<fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        
    <fullName>Store__c</fullName>
        
        
    <label>Store</label>
        
    <referenceTo>Store__c</referenceTo>
        
    <relationshipLabel>Supplier Orders</relationshipLabel>
        
    <relationshipName>Supplier_Orders</relationshipName>
        
    <relationshipOrder>0</relationshipOrder>
        
        
        
        
    <type>MasterDetail</type>
        
        
</fields>
    <fields>
        
    <fullName>Supplier__c</fullName>
        
        
    <label>Supplier</label>
        
    <referenceTo>Supplier__c</referenceTo>
        
    <relationshipLabel>Supplier Orders</relationshipLabel>
        
    <relationshipName>Supplier_Orders</relationshipName>
        
    <relationshipOrder>1</relationshipOrder>
        
        
        
        
    <type>MasterDetail</type>
        
        
</fields>
</CustomObject>

force-app/main/default/classes/SupplierController.cls
/**************************************************************
* SupplierController.apxc
* Author: Evan DeVizio
* Created: 8/10/21
* Modified: 8/15/21
***************************************************************/
public with sharing class SupplierController {
    
    @AuraEnabled
    public static List<Supplier__c> getSupplierObjs() {
        List<Supplier__c> suppObjList = new List<Supplier__c>();
        if(Schema.SObjectType.Supplier__c.isAccessible()) {
            for(Supplier__c supplier : [SELECT Id, Name, Email__c, Phone__c, Street_Address__c,
                                        City__c, State__c, Zip__c, Website__c FROM Supplier__c]) {
                                            
                suppObjList.add(supplier);
            }
        } 
        else {
            throw new AuraHandledException('You do not have access to the Supplier object.');
        }
        return suppObjList;
    }
    
    @AuraEnabled
    public static List<Supplier_Order__c> getSupplierOrders() {
        List<Supplier_Order__c> suppOrderList = new List<Supplier_Order__c>();
        if(Schema.SObjectType.Supplier_Order__c.isAccessible()) {
            for(Supplier_Order__c suppOrder : [SELECT Name, Store__c, Cost__c FROM Supplier_Order__c]) {
                suppOrderList.add(suppOrder);
            }
        } 
        else {
            throw new AuraHandledException('You do not have access to the Supplier Order object.');
        }
        return suppOrderList;
    }
}