mdapi_output_dir/objects/Store__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Store</label>
    
    <nameField>
        
        <label>Store Name</label>
        
        
        <type>Text</type>
        
    </nameField>
    
    <pluralLabel>Stores</pluralLabel>
    
    
    <sharingModel>ReadWrite</sharingModel>
    
    
<fields>
        
    <fullName>City__c</fullName>
        
        
    <label>City</label>
        
    <length>40</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Phone__c</fullName>
        
        
    <label>Phone</label>
        
        
        
        
    <type>Phone</type>
        
</fields>
    <fields>
        
    <fullName>State__c</fullName>
        
        
    <inlineHelpText>Only use the initials for the state i.e. GA - Georgia</inlineHelpText>
        
    <label>State</label>
        
    <length>2</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Store_Owner__c</fullName>
        
    <deleteConstraint>SetNull</deleteConstraint>
        
        
    <label>Store Owner</label>
        
    <referenceTo>Store_Owner__c</referenceTo>
        
    <relationshipLabel>Stores</relationshipLabel>
        
    <relationshipName>Stores</relationshipName>
        
        
        
        
    <type>Lookup</type>
        
</fields>
    <fields>
        
    <fullName>Street_Address__c</fullName>
        
        
    <label>Street Address</label>
        
    <length>40</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
    <fields>
        
    <fullName>Zip__c</fullName>
        
        
    <label>Zip</label>
        
    <length>10</length>
        
        
        
        
    <type>Text</type>
        
        
</fields>
</CustomObject>

mdapi_output_dir/objects/Store_Owner__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Store Owner</label>
    
    <nameField>
        
        <label>Store Owner Name</label>
        
        
        <type>Text</type>
        
    </nameField>
    
    <pluralLabel>Store Owners</pluralLabel>
    
    
    <sharingModel>ControlledByParent</sharingModel>
    
    
    <fields>
        
    <fullName>Phone__c</fullName>
        
        
    <label>Phone</label>
        
        
        
        
    <type>Phone</type>
        
</fields>
    <fields>
        
    <fullName>Store__c</fullName>
        
        
    <label>Store</label>
        
    <referenceTo>Store__c</referenceTo>
        
    <relationshipLabel>Store Owner</relationshipLabel>
        
    <relationshipName>Store_Owners</relationshipName>
        
    <relationshipOrder>0</relationshipOrder>
        
        
        
        
    <type>MasterDetail</type>
        
        
</fields>
</CustomObject>

force-app/main/default/classes/InventoryController.cls
/**************************************************************
* InventoryController.apxc
* Author: Evan DeVizio
* Created: 8/16/21
* Modified: 8/16/21
* Purpose: Interact with Salesforce database to retrieve stores.
***************************************************************/
public with sharing class InventoryController {
	@AuraEnabled
    public static List<Store__c> getStores() {
        List<Store__c> storeList = new List<Store__c>();
        if(Schema.SObjectType.Store__c.isAccessible()) {
            for(Store__c store : [SELECT Id, Name, Store_Owner__c, Phone__c, Street_Address__c,
                                        City__c, State__c, Zip__c, Website__c FROM Store__c]) {
                                            
            	storeList.add(store);
            }
        } 
        else {
            throw new AuraHandledException('You do not have access to the Store object.');
        }
        return storeList;
    }
}