mdapi_output_dir/objects/Store__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Store</label>
    
    <nameField>
        
        <label>Store Name</label>
        
        
        <type>Text</type>
        
    </nameField>
    
    <pluralLabel>Stores</pluralLabel>
    
    
    <sharingModel>ReadWrite</sharingModel>
    
    
</CustomObject>

mdapi_output_dir/objects/Transaction__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Transaction</label>
    
    <nameField>
        
        <displayFormat>Transaction-{00000}</displayFormat>
        
        <label>Transaction Number</label>
        
        
        <type>AutoNumber</type>
        
    </nameField>
    
    <pluralLabel>Transactions</pluralLabel>
    
    
    <sharingModel>ControlledByParent</sharingModel>
    
    
    <fields>
        
    <fullName>Store__c</fullName>
        
        
    <label>Store</label>
        
    <referenceTo>Store__c</referenceTo>
        
    <relationshipLabel>Transactions</relationshipLabel>
        
    <relationshipName>Transactions</relationshipName>
        
    <relationshipOrder>0</relationshipOrder>
        
        
        
        
    <type>MasterDetail</type>
        
        
</fields>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_Time__c</fullName>
    <label>Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TransactionControllerTest.cls
@isTest
public class TransactionControllerTest {
	@isTest
    static void TransControllerTest() {
        //Create test data
        Store__c s = new Store__c(Name = 'testStore');
        insert s;
        
        Transaction__c t = new Transaction__c();
        t.Date_Time__c = Datetime.now();
        t.Store__c = s.Id;
        
        //Start test
        System.Test.startTest();
        
        Database.SaveResult sr = Database.insert(t);
        
        //Query transaction record name
       	List<Transaction__c> n = [SELECT Name FROM Transaction__c LIMIT 1];
        
        //Create an instance of TransactionController
        TransactionController tc = new TransactionController();
        tc.myInput = n[0].Name; //Pass in queried transaction name
        tc.search(); //Call search method in controller
        
        //Verify subtotal
        system.assertEquals(null, tc.subTotal);
        
        //End test
        System.Test.stopTest();
        
    }
}