mdapi_output_dir/objects/Supplier_Order__c.object
<CustomObject>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <label>Supplier Order</label>
    
    <nameField>
        
        <label>Supplier Order Name</label>
        
        
        <type>Text</type>
        
    </nameField>
    
    <pluralLabel>Supplier Orders</pluralLabel>
    
    
    <sharingModel>ControlledByParent</sharingModel>
    
    
<fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        
    <fullName>Quantity__c</fullName>
        
        
    <label>Quantity</label>
        
    <precision>18</precision>
        
        
    <scale>0</scale>
        
        
        
    <type>Number</type>
        
        
</fields>
    <fields>
        
    <fullName>Shipping_Address__c</fullName>
        
        
        
    <label>Shipping Address</label>
        
    <length>100</length>
        
        
        
        
    <type>Text</type>
        
    <unique>true</unique>
        
</fields>
</CustomObject>

main/default/classes/SuplierOrder.cls
/* Project 1
 * Author: Endalkachew Filfilu
 * Date: 07/28/2021
 * The intent: The supplier order is custom object
 * This class will access the Object and the fields
 * the task will be implementing the page that displays
   the fields  with customized view on visualforce page
*/

public class SuplierOrder {
    Supplier_Order__c sup= new Supplier_Order__c();
    public List<Supplier_Order__c> supplierLis = new List<Supplier_Order__c>();
    public List<Supplier_Order__c> spplier{get; set;}
    public SuplierOrder(){
        spplier =new List<Supplier_Order__c>();
        spplier.add(sup);
    }
    
    public void getFields(){
   List<Supplier_Order__c> supfields=[SELECT Shipping_Address__c,Name, Cost__c,Quantity__c FROM Supplier_Order__c];
        for(Supplier_Order__c spp: supfields){
            Supplier_Order__c suplier = new Supplier_Order__c();
            suplier.Name = spp.Name;
            supplierLis.add(suplier);
           
        }
        
    }
    
    
    
    
    

}